var cities = [
"Sydney", "Sydney",
"Albury", "Albury",
"Armidale", "Armidale",
"Bathurst", "Bathurst",
"Blue Mountains", "Blue Mountains",
"Broken Hill", "Broken Hill",
"Campbelltown", "Campbelltown",
"Cessnock", "Cessnock",
"Dubbo", "Dubbo",
"Goulburn", "Goulburn",
"Grafton", "Grafton",
"Lithgow", "Lithgow",
"Liverpool", "Liverpool",
"Newcastle", "Newcastle",
"Orange", "Orange",
"Parramatta", "Parramatta",
"Penrith", "Penrith",
"Queanbeyan", "Queanbeyan",
"Darwin", "Darwin",
"Palmerston", "Palmerston",
"Brisbane", "Brisbane",
"Bundaberg", "Bundaberg",
"Caboolture", "Caboolture",
"Cairns", "Cairns",
"Caloundra", "Caloundra",
"Gladstone", "Gladstone",
"Gold Coast", "Gold Coast",
"Gympie", "Gympie",
"Hervey Bay", "Hervey Bay",
"Ipswich", "Ipswich",
"Logan City", "Logan City",
"Mackay", "Mackay",
"Maryborough", "Maryborough",
"Mount Isa", "Mount Isa",
"Rockhampton", "Rockhampton",
"Sunshine Coast", "Sunshine Coast",
"Toowoomba", "Toowoomba",
"Townsville", "Townsville",
"Charters Towers", "Charters Towers",
"Redcliffe City", "Redcliffe City",
"Redland City", "Redland City",
"Thuringowa", "Thuringowa",
"Warwick", "Warwick",
"Adelaide", "Adelaide",
"Mount Barker", "Mount Barker",
"Mount Gambier", "Mount Gambier",
"Murray Bridge", "Murray Bridge",
"Port Adelaide", "Port Adelaide",
"Port Augusta", "Port Augusta",
"Port Pirie", "Port Pirie",
"Port Lincoln", "Port Lincoln",
"Victor Harbor", "Victor Harbor",
"Hobart", "Hobart",
"Burnie", "Burnie",
"Devonport", "Devonport",
"Launceston", "Launceston",
"Melbourne", "Melbourne",
"Ararat", "Ararat",
"Bairnsdale", "Bairnsdale",
"Benalla", "Benalla",
"Ballarat", "Ballarat",
"Bendigo", "Bendigo",
"Dandenong", "Dandenong",
"Frankston", "Frankston",
"Geelong", "Geelong",
"Hamilton", "Hamilton",
"Horsham", "Horsham",
"Latrobe City", "Latrobe City",
"Melton", "Melton",
"Mildura", "Mildura",
"Sale", "Sale",
"Shepparton", "Shepparton",
"Swan Hill", "Swan Hill",
"Wangaratta", "Wangaratta",
"Warrnambool", "Warrnambool",
"Wodonga", "Wodonga",
"Perth", "Perth",
"Albany", "Albany",
"Bunbury", "Bunbury",
"Busselton", "Busselton",
"Fremantle", "Fremantle",
"Geraldton", "Geraldton",
"Joondalup", "Joondalup",
"Kalgoorlie", "Kalgoorlie",
"Mandurah", "Mandurah"
];